github: Sanjai-Shaarugesh
patreon: Sanjai-Shaarugesh
open_collective: Sanjai-Shaarugesh
ko_fi: Sanjai-Shaarugesh
tidelift: npm/Sanjai-Shaarugesh
community_bridge: Sanjai-Shaarugesh
liberapay: Sanjai-Shaarugesh
issuehunt: Sanjai-Shaarugesh
lfx_crowdfunding: Sanjai-Shaarugesh
polar: Sanjai-Shaarugesh
buy_me_a_coffee: Sanjai-Shaarugesh
thanks_dev: Sanjai-Shaarugesh
stripe: https://buy.stripe.com/test_5kAeXTaQzgHpbBK7ss
